browser=chrome
productName=ADIDAS ORIGINAL
productName1=ZARA COAT 3
countryName=India
orderPageUrl=https://rahulshettyacademy.com/client/#/dashboard/myorders
cartPageUrl=https://rahulshettyacademy.com/client/#/dashboard/cart